# Generated by Django 2.0.6 on 2018-07-02 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('complaint', '0001_initial'),
        ('communities', '0002_auto_20180702_1441'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thoughtcomplaintset',
            name='thought',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_set', to='users.Thought'),
        ),
        migrations.AddField(
            model_name='thoughtcomplaint',
            name='complainant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_complaints_thought', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thoughtcomplaint',
            name='complaintSet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='complaint.ThoughtComplaintSet'),
        ),
        migrations.AddField(
            model_name='newscomplaintset',
            name='news',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_set', to='communities.News'),
        ),
        migrations.AddField(
            model_name='newscomplaint',
            name='complainant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_complaints_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newscomplaint',
            name='complaintSet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='complaint.NewsComplaintSet'),
        ),
    ]
