# Generated by Django 2.0.7 on 2018-07-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180702_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
    ]
