# Generated by Django 2.0.7 on 2018-08-01 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_personalinfo_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='dob',
        ),
    ]
