# Generated by Django 2.0.7 on 2018-08-02 02:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_personalinfo_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='language',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=7), blank=True, null=True, size=None),
        ),
    ]
