# Generated by Django 2.0.7 on 2018-08-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_personalinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicture',
            name='picture',
            field=models.ImageField(upload_to='upics'),
        ),
    ]
