# Generated by Django 2.0.7 on 2018-08-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180810_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='status'),
        ),
    ]
