# Generated by Django 2.0.7 on 2018-08-17 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180811_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='useralbum',
            name='mainPicture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_Main_For', to='users.UserPicture'),
        ),
    ]
