# Generated by Django 2.0.7 on 2018-08-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_useralbum_mainpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(blank=True, default='n', max_length=1, null=True),
        ),
    ]
