# Generated by Django 2.0.6 on 2018-07-02 14:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=100)),
                ('custom', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'CommAssessment',
                'verbose_name_plural': 'CommAssessments',
            },
        ),
        migrations.CreateModel(
            name='CommBreakingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nOfExtDugsPropBreakings', models.IntegerField(default=0)),
                ('nOfSuicCallBreakings', models.IntegerField(default=0)),
                ('nOfDiscreditBreakings', models.IntegerField(default=0)),
                ('nOfAdultContentBreakings', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'CommunityBreakingHistory',
                'verbose_name_plural': 'CommunityBreakingHistories',
            },
        ),
        migrations.CreateModel(
            name='CommGovernance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'CommGovernance',
                'verbose_name_plural': 'CommGovernances',
            },
        ),
        migrations.CreateModel(
            name='CommPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('picture', models.ImageField(upload_to='')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='communities.CommAlbum')),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isBanned', models.BooleanField(default=False)),
                ('bannedTill', models.DateField(null=True)),
                ('name', models.CharField(max_length=20)),
                ('finalRating', models.FloatField()),
                ('nOfMembers', models.IntegerField()),
            ],
            options={
                'verbose_name': 'community',
                'verbose_name_plural': 'communities',
            },
        ),
        migrations.CreateModel(
            name='CommunityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=35)),
                ('contentType', models.CharField(choices=[('mm', 'Mass media'), ('ent', 'Entertainment'), ('bl', 'Blog')], max_length=5)),
                ('description', models.CharField(max_length=100)),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_Info', to='communities.Community')),
            ],
            options={
                'verbose_name': 'CommunityInfo',
                'verbose_name_plural': 'CommunityInfos',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDeleted', models.BooleanField()),
                ('time', models.DateTimeField()),
                ('isTemporary', models.BooleanField()),
                ('expiresOn', models.DateTimeField()),
                ('content', models.CharField(max_length=900)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='communities.Community')),
                ('pictures', models.ManyToManyField(related_name='attached_To', to='communities.CommPicture')),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
            },
        ),
    ]
