# Generated by Django 2.0.6 on 2018-07-02 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commgovernance',
            name='admins',
            field=models.ManyToManyField(related_name='managed_communities_governances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commgovernance',
            name='community',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='governance', to='communities.Community'),
        ),
        migrations.AddField(
            model_name='commgovernance',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_Communities_Governances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commgovernance',
            name='mainAdmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruled_communities_governances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commbreakinghistory',
            name='community',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breaking_History', to='communities.Community'),
        ),
        migrations.AddField(
            model_name='commassessment',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_Community_Assessments', to='communities.Community'),
        ),
        migrations.AddField(
            model_name='commassessment',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_Community_Assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commalbum',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='communities.Community'),
        ),
    ]
