# Generated by Django 2.0.7 on 2018-08-17 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_auto_20180702_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='commalbum',
            name='mainPicture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_Main_For', to='communities.CommPicture'),
        ),
    ]
