# Generated by Django 2.0.6 on 2018-07-02 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('foundUsingMeetMate', models.BooleanField()),
                ('firstMeetMateForOneOfUsers', models.BooleanField()),
                ('messagesTotal', models.BigIntegerField(default=0)),
                ('deletedForFirstUser', models.BooleanField(default=False)),
                ('deletedForSecondUser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(max_length=512)),
                ('isRead', models.BooleanField(default=False)),
                ('isDeletedBySender', models.BooleanField(default=False)),
                ('isDeletedByReceiver', models.BooleanField(default=False)),
                ('time', models.DateTimeField(verbose_name='When message was sent')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.Conversation')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
    ]
