# Generated by Django 2.0.6 on 2018-07-02 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messageReceiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='messageSender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='firstConversationUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_where_first', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='secondConversationUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_where_second', to=settings.AUTH_USER_MODEL),
        ),
    ]
