# Generated by Django 2.0.6 on 2018-07-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dayGrowth', models.FloatField()),
                ('totalUsers', models.IntegerField()),
                ('activeUsersPercentage', models.IntegerField()),
                ('usersRegisteredToday', models.IntegerField()),
                ('succesfulMeetMates', models.IntegerField()),
                ('thoughtsNumber', models.IntegerField()),
                ('MeetMateQuality', models.IntegerField()),
                ('MeetMatePerActiveUser', models.IntegerField()),
                ('RateMatePerActiveUsre', models.IntegerField()),
                ('ThoughtPerAvtiveUser', models.IntegerField()),
            ],
            options={
                'verbose_name': 'dayMetrics',
                'verbose_name_plural': 'dayMetrics',
            },
        ),
        migrations.CreateModel(
            name='MonthMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('monthGrowth', models.FloatField()),
                ('totalUsers', models.IntegerField()),
                ('activeUsersPercentage', models.IntegerField()),
                ('usersRegisteredThisMonth', models.IntegerField()),
                ('MeetMateQuality', models.IntegerField()),
                ('MeetMatePerActiveUser', models.IntegerField()),
                ('RateMatePerActiveUsre', models.IntegerField()),
                ('ThoughtPerAvtiveUser', models.IntegerField()),
            ],
            options={
                'verbose_name': 'monthMetrics',
                'verbose_name_plural': 'monthMetrics',
            },
        ),
        migrations.CreateModel(
            name='WeekMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weekGrowth', models.FloatField()),
                ('totalUsers', models.IntegerField()),
                ('activeUsersPercentage', models.IntegerField()),
                ('usersRegisteredThisWeek', models.IntegerField()),
                ('MeetMateQuality', models.IntegerField()),
                ('MeetMatePerActiveUser', models.IntegerField()),
                ('RateMatePerActiveUsre', models.IntegerField()),
                ('ThoughtPerAvtiveUser', models.IntegerField()),
            ],
            options={
                'verbose_name': 'weekMetrics',
                'verbose_name_plural': 'weekMetrics',
            },
        ),
    ]
