# Generated by Django 2.0.6 on 2018-07-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erudition', models.IntegerField()),
                ('candor', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('senseOfHumour', models.IntegerField()),
            ],
            options={
                'verbose_name': 'userAssessment',
                'verbose_name_plural': 'userAssessments',
            },
        ),
    ]
